#!/bin/sh

# wrap-for-bin.sh: Template for git executable wrapper scripts
# to run test suite against sandbox, but with only bindir-installed
# executables in PATH.  The Makefile copies this into various
# files in bin-wrappers, substituting
# /home/ec2-user/git-2.39.0 and scalar.

GIT_EXEC_PATH='/home/ec2-user/git-2.39.0'
if test -n "$NO_SET_GIT_TEMPLATE_DIR"
then
	unset GIT_TEMPLATE_DIR
else
	GIT_TEMPLATE_DIR='/home/ec2-user/git-2.39.0/templates/blt'
	export GIT_TEMPLATE_DIR
fi
GITPERLLIB='/home/ec2-user/git-2.39.0/perl/build/lib'"${GITPERLLIB:+:$GITPERLLIB}"
GIT_TEXTDOMAINDIR='/home/ec2-user/git-2.39.0/po/build/locale'
PATH='/home/ec2-user/git-2.39.0/bin-wrappers:'"$PATH"

export GIT_EXEC_PATH GITPERLLIB PATH GIT_TEXTDOMAINDIR

case "$GIT_DEBUGGER" in
'')
	exec "${GIT_EXEC_PATH}/scalar" "$@"
	;;
1)
	unset GIT_DEBUGGER
	exec gdb --args "${GIT_EXEC_PATH}/scalar" "$@"
	;;
*)
	GIT_DEBUGGER_ARGS="$GIT_DEBUGGER"
	unset GIT_DEBUGGER
	exec ${GIT_DEBUGGER_ARGS} "${GIT_EXEC_PATH}/scalar" "$@"
	;;
esac
